### ISSUE TITLE
Error in classification.py

### ISSUE THREAD

**Issue by sdsdjr** [scilearn/FSHDMR#2]
Hello,
When I run classification.py I get this errors:
Skipping ../results/INDIANPINES_accuracy_hdmr_svm.mat
Skipping ../results/INDIANPINES_accuracy_fisher_svm.mat
Skipping ../results/INDIANPINES_accuracy_svmrfe_svm.mat
Skipping ../results/INDIANPINES_accuracy_relieff_svm.mat
Skipping ../results/INDIANPINES_accuracy_mrmr_svm.mat
Skipping ../results/INDIANPINES_accuracy_jmi_svm.mat
Skipping ../results/INDIANPINES_accuracy_infogain_svm.mat
C:\Users\User\.vscode\extensions\donjayamanne.python-0.6.4\pythonFiles\PythonTools\visualstudio_py_debugger.py:2202: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  return hex(obj)
Traceback (most recent call last):
  File "d:\MPCode\fshdmr\src\classification.py", line 104, in <module>
    main()
  File "d:\MPCode\fshdmr\src\classification.py", line 22, in main
============
or run it under cmd command  
D:\MPCode\fshdmr\src>python classification.py
Skipping ../results/INDIANPINES_accuracy_hdmr_bayes.mat
Skipping ../results/INDIANPINES_accuracy_jmi_bayes.mat
Skipping ../results/INDIANPINES_accuracy_svmrfe_bayes.mat
Skipping ../results/INDIANPINES_accuracy_infogain_bayes.mat
Skipping ../results/INDIANPINES_accuracy_mrmr_bayes.mat
Skipping ../results/INDIANPINES_accuracy_relieff_bayes.mat
Traceback (most recent call last):
  File "classification.py", line 104, in <module>
    main()
  File "classification.py", line 22, in main
    classification(method,classifier,dataset)
  File "classification.py", line 52, in classification
    frange[len(frange)-1]=n_features
TypeError: 'range' object does not support item assignment
====================

Thanks

**Comment by sdsdjr** [comment]
Hello,
The problem fixed with this change in classification.py
  frange=list(range(5,n_features,5))
now it can run under python 3

**Comment by hkayabilisim** [comment]
Thank you for fix. I modified the file accordingly.

**Comment by sdsdjr** [comment]
Dear Mr. Huseyin Kaya,
May I have your email, I have a question about extending this project
my Email is sdsdjr@gmail.com
thank you

**Comment by hkayabilisim** [comment]
You can send to hkayabilisim@gmail.com
