### ISSUE TITLE
preparing firures

### ISSUE THREAD

**Issue by sdsdjr** [scilearn/FSHDMR#3]
Hello,
When I run the visualizeAccuracyAllinOne.m in matlab the following error will be raised

Undefined function or variable 'export_fig'.

Error in visualizeAccuracyAllinOne (line 75)
export_fig('../figures/accuracyAllinOne.pdf')

**Comment by hkayabilisim** [comment]
You should install the export_fig package first. That should be noted in the readme file. It is a well known matlab package.

**Comment by sdsdjr** [comment]
Thank you,
Also, I had to download the Ghostscript (gs921w64.exe) on my computer.

**Comment by hkayabilisim** [comment]
That was the requirement of export_fig if I remember correctly.
